### ISSUE TITLE
Conformance Tests for CNAB Runtimes

### ISSUE THREAD

**Issue by astrieanna** [cnabio/cnab-spec#213] opened 2019-07-01 21:35 UTC
## The Problem
Because the CNAB spec is a complex document written in english and translated into implementations by humans, there is a risk of differences between runtime implementations (through misunderstandings, mistakes, etc). A common suite of tests for all CNAB runtimes would help runtime authors validate that they have correctly implemented the spec.

## Test Structure
An approach to this testing could involve a set of bundles, configs for those bundles, and the expected outputs (or stdout logs). The test is that running the specified action on the specified image with specified config will result in the expected output. This would be a good match for things like testing that all the config gets into the invocation image as expected.

The challenge to running these tests across runtimes is that there is no spec for how to ask a runtime to do something with a bundle and then get the results. One approach to work around this would be to have an interface for the required actions on a runtime. E.g. if the test suite were written in Go, then there would be an interface for each runtime to implement with `InstallBundle(bundle, config)` or something similar. The runtimes would need to write a small shim to run the basic commands to be compatible with the test suite.

cc @ryanmoran

**Comment by technosophos** [comment] 2020-02-13 00:04
Is anyone working on this? The issue seems to have gone stale.

**Comment by technosophos** [comment] 2020-02-13 00:16
Closed as a duplicate of #27

**Closed by technosophos** 2020-02-13 00:16 UTC
